### ISSUE TITLE
Colors not rendered and unhandled exception on Lollipop 

### ISSUE THREAD

**Issue by astrazzari72** [Cheesebaron/Cheesebaron.ColorPickers#3]
The colors square results full gray and after some interactions it causes an unhandled exception

**Comment by astrazzari72** [comment]
Stack trace:
09-04 18:09:56.065 I/MonoDroid(22338): UNHANDLED EXCEPTION:
09-04 18:09:56.065 I/art     (22338): Clamp target GC heap from 143MB to 128MB
09-04 18:09:56.075 I/art     (22338): Alloc partial concurrent mark sweep GC freed 9(400B) AllocSpace objects, 0(0B) LOS objects, 0% free, 127MB/128MB, paused 1.154ms total 17.691ms
09-04 18:09:56.075 I/art     (22338): WaitForGcToComplete blocked for 46.967ms for cause Alloc
09-04 18:09:56.075 I/art     (22338): Alloc sticky concurrent mark sweep GC freed 2(96B) AllocSpace objects, 0(0B) LOS objects, 0% free, 127MB/128MB, paused 1.040ms total 5.348ms
09-04 18:09:56.075 I/art     (22338): WaitForGcToComplete blocked for 30.273ms for cause Alloc
09-04 18:09:56.085 I/MonoDroid(22338): Java.Lang.OutOfMemoryError: Exception of type 'Java.Lang.OutOfMemoryError' was thrown.
09-04 18:09:56.085 I/MonoDroid(22338): at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <IL 0x00011, 0x0004b>
09-04 18:09:56.085 I/MonoDroid(22338): at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (object) <IL 0x00006, 0x0003b>
09-04 18:09:56.085 I/MonoDroid(22338): at Android.App.SyncContext/<Post>c__AnonStorey0.<>m__0 () [0x00000] in /Users/builder/data/lanes/1879/5f55a9ef/source/monodroid/src/Mono.Android/src/Android.App/SyncContext.cs:18
09-04 18:09:56.085 I/MonoDroid(22338): at Java.Lang.Thread/RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/1879/5f55a9ef/source/monodroid/src/Mono.Android/src/Java.Lang/Thread.cs:36
09-04 18:09:56.085 I/MonoDroid(22338): at Java.Lang.IRunnableInvoker.n_Run (intptr,intptr) [0x00009] in /Users/builder/data/lanes/1879/5f55a9ef/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Java.Lang.IRunnable.cs:71
09-04 18:09:56.085 I/MonoDroid(22338): at (wrapper dynamic-method) object.fa5faf04-ef88-453e-b7cd-6c6df146c5e6 (intptr,intptr) <IL 0x00011, 0x0001f>
09-04 18:09:56.085 I/MonoDroid(22338):   --- End of managed exception stack trace ---
09-04 18:09:56.085 I/MonoDroid(22338): java.lang.OutOfMemoryError: Failed to allocate a 1048588 byte allocation with 342216 free bytes and 334KB until OOM
09-04 18:09:56.085 I/MonoDroid(22338): 	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
09-04 18:09:56.085 I/MonoDroid(22338): 	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
09-04 18:09:56.085 I/MonoDroid(22338): 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
09-04 18:09:56.085 I/MonoDroid(22338): 	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
09-04 18:09:56.085 I/MonoDroid(22338): 	at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:467)
09-04 18:09:56.085 I/MonoDroid(22338): 	at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:497)
09-04 18:09:56.095 D/AndroidRuntime(22338): Shutting down VM
09-04 18:09:56.115 I/art     (22338): Clamp target GC heap from 143MB to 128MB
09-04 18:09:56.115 I/art     (22338): Alloc concurrent mark sweep GC freed 78(8KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 127MB/128MB, paused 1.015ms total 37.940ms
09-04 18:09:56.115 I/art     (22338): WaitForGcToComplete blocked for 41.622ms for cause Alloc
09-04 18:09:56.115 E/art     (22338): Throwing OutOfMemoryError "Failed to allocate a 1048588 byte allocation with 338424 free bytes and 330KB until OOM"
09-04 18:09:56.125 D/skia    (22338): --- allocation failed for scaled bitmap
09-04 18:09:56.145 I/art     (22338): Clamp target GC heap from 143MB to 128MB
09-04 18:09:56.145 I/art     (22338): Alloc concurrent mark sweep GC freed 14(496B) AllocSpace objects, 0(0B) LOS objects, 0% free, 127MB/128MB, paused 534us total 29.410ms
09-04 18:09:56.145 I/art     (22338): Forcing collection of SoftReferences for 1024KB allocation
09-04 18:09:56.145 I/art     (22338): WaitForGcToComplete blocked for 59.291ms for cause Alloc
09-04 18:09:56.165 I/art     (22338): Clamp target GC heap from 143MB to 128MB
An unhandled exception occured.

09-04 18:09:56.165 I/art     (22338): Alloc partial concurrent mark sweep GC freed 5(240B) AllocSpace objects, 0(0B) LOS objects, 0% free, 127MB/128MB, paused 769us total 15.426ms
09-04 18:09:56.195 I/art     (22338): Clamp target GC heap from 143MB to 128MB
09-04 18:09:56.195 I/art     (22338): Alloc concurrent mark sweep GC freed 4(160B) AllocSpace objects, 0(0B) LOS objects, 0% free, 127MB/128MB, paused 949us total 28.324ms
09-04 18:09:56.195 I/art     (22338): Forcing collection of SoftReferences for 1024KB allocation
09-04 18:09:56.195 I/art     (22338): WaitForGcToComplete blocked for 44.525ms for cause Alloc
09-04 18:09:56.215 I/art     (22338): Clamp target GC heap from 143MB to 128MB
09-04 18:09:56.215 I/art     (22338): Alloc concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 0% free, 127MB/128MB, paused 469us total 26.263ms
09-04 18:09:56.215 I/art     (22338): WaitForGcToComplete blocked for 25.947ms for cause Alloc
09-04 18:09:56.225 E/art     (22338): Throwing OutOfMemoryError "Failed to allocate a 1048588 byte allocation with 338776 free bytes and 330KB until OOM"
09-04 18:09:56.225 D/skia    (22338): --- allocation failed for scaled bitmap
09-04 18:09:56.245 I/art     (22338): Clamp target GC heap from 143MB to 128MB
09-04 18:09:56.245 I/art     (22338): Alloc concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 0% free, 127MB/128MB, paused 570us total 26.699ms
09-04 18:09:56.245 E/art     (22338): Throwing OutOfMemoryError "Failed to allocate a 1048588 byte allocation with 338424 free bytes and 330KB until OOM"
09-04 18:09:56.245 D/skia    (22338): --- allocation failed for scaled bitmap
09-04 18:10:01.105 E/AndroidRuntime(22338): FATAL EXCEPTION: main
09-04 18:10:01.105 E/AndroidRuntime(22338): Process: com.logicasistemi.paintanatomy, PID: 22338
09-04 18:10:01.105 E/AndroidRuntime(22338): java.lang.OutOfMemoryError: Failed to allocate a 1048588 byte allocation with 342216 free bytes and 334KB until OOM
09-04 18:10:01.105 E/AndroidRuntime(22338): 	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
09-04 18:10:01.105 E/AndroidRuntime(22338): 	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
09-04 18:10:01.105 E/AndroidRuntime(22338): 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
09-04 18:10:01.105 E/AndroidRuntime(22338): 	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
09-04 18:10:01.105 E/AndroidRuntime(22338): 	at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:467)
09-04 18:10:01.105 E/AndroidRuntime(22338): 	at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:497)
09-04 18:10:01.125 I/art     (22338): Alloc sticky concurrent mark sweep GC freed 90(14KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 127MB/128MB, paused 1.139ms total 8.698ms
09-04 18:10:01.145 I/art     (22338): Clamp target GC heap from 143MB to 128MB
09-04 18:10:01.145 I/art     (22338): Alloc partial concurrent mark sweep GC freed 20(880B) AllocSpace objects, 0(0B) LOS objects, 0% free, 127MB/128MB, paused 608us total 23.921ms
09-04 18:10:01.155 I/art     (22338): WaitForGcToComplete blocked for 25.968ms for cause Alloc
09-04 18:10:01.175 I/art     (22338): Clamp target GC heap from 143MB to 128MB
09-04 18:10:01.175 I/art     (22338): Alloc partial concurrent mark sweep GC freed 10(416B) AllocSpace objects, 0(0B) LOS objects, 0% free, 127MB/128MB, paused 592us total 19.951ms
09-04 18:10:01.175 I/art     (22338): WaitForGcToComplete blocked for 13.581ms for cause Alloc
09-04 18:10:01.205 I/art     (22338): Clamp target GC heap from 143MB to 128MB
09-04 18:10:01.205 I/art     (22338): Alloc concurrent mark sweep GC freed 2(64B) AllocSpace objects, 0(0B) LOS objects, 0% free, 127MB/128MB, paused 863us total 34.534ms
09-04 18:10:01.205 I/art     (22338): WaitForGcToComplete blocked for 33.745ms for cause Alloc
09-04 18:10:01.205 I/art     (22338): Forcing collection of SoftReferences for 1024KB allocation
09-04 18:10:01.245 I/art     (22338): Clamp target GC heap from 143MB to 128MB
09-04 18:10:01.245 I/art     (22338): Alloc concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 0% free, 127MB/128MB, paused 722us total 42.455ms
09-04 18:10:01.245 I/art     (22338): Forcing collection of SoftReferences for 1024KB allocation
09-04 18:10:01.275 I/art     (22338): Clamp target GC heap from 143MB to 128MB
09-04 18:10:01.275 I/art     (22338): Alloc concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 0% free, 127MB/128MB, paused 600us total 29.270ms
09-04 18:10:01.275 E/art     (22338): Throwing OutOfMemoryError "Failed to allocate a 1048588 byte allocation with 335800 free bytes and 327KB until OOM"
09-04 18:10:01.275 I/art     (22338): WaitForGcToComplete blocked for 70.999ms for cause Alloc
09-04 18:10:01.275 D/skia    (22338): --- allocation failed for scaled bitmap
09-04 18:10:01.305 I/art     (22338): Clamp target GC heap from 143MB to 128MB
09-04 18:10:01.305 I/art     (22338): Alloc concurrent mark sweep GC freed 10(432B) AllocSpace objects, 0(0B) LOS objects, 0% free, 127MB/128MB, paused 720us total 29.762ms
09-04 18:10:01.305 E/art     (22338): Throwing OutOfMemoryError "Failed to allocate a 1048588 byte allocation with 335608 free bytes and 327KB until OOM"
09-04 18:10:01.305 D/skia    (22338): --- allocation failed for scaled bitmap
09-04 18:10:07.145 I/art     (22338): Clamp target GC heap from 135MB to 128MB
09-04 18:10:10.395 I/Process (22338): Sending signal. PID: 22338 SIG: 9

**Comment by Cheesebaron** [comment]
Pull requests with fixes are very welcome. I haven't looked or worked on this for a looooooooooong time.
