### ISSUE TITLE
Does this work with AndroidX

### ISSUE THREAD

**Issue by CDrosos** [Cheesebaron/Cheesebaron.ColorPickers#4]
are you planning to maintain the support in this plugin? does it work with the latest android versions?

**Comment by Cheesebaron** [comment]
Hmm haven't touched this in forever. When I look at the code it _should_ just work. It doesn't have any dependencies like Support libraries or AndroidX.

Would you like me to fix this up and publish it as a NuGet?

**Comment by CDrosos** [comment]
yes please

**Comment by Cheesebaron** [comment]
![Annotation 2020-03-30 144650](https://user-images.githubusercontent.com/249719/77913868-503ba080-7295-11ea-8dc8-1f1e7356c334.png)

Seems to run. Will work on packing it up as a NuGet package :)

**Comment by Cheesebaron** [comment]
NuGet package here: https://www.nuget.org/packages/Cheesebaron.ColorPickers/
